### ISSUE TITLE
Default protocol

### ISSUE THREAD

**Issue by ghost** [NickCarneiro/curlconverter#169]
This is a valid cURL command:

~~~
curl -I example.com
~~~

but produces this:

~~~
Error parsing curl command.
~~~

**Comment by clintonc** [comment]
I would like to work on this.

**Comment by clintonc** [comment]
I'll note that the behavior at HEAD on master seems different: curl -I example.com becomes a regular GET.

**Comment by clintonc** [comment]
The problem occurs when one omits the protocol; `curl -I http://example.com` works fine.

Here is the full stack trace for the given command:

```
internal/validators.js:107
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.parseCurlCommand (/Users/clintonc/curlconverter/util.js:145:23)
    at Object.toPython (/Users/clintonc/curlconverter/generators/python.js:117:22)
    at Object.<anonymous> (/Users/clintonc/curlconverter/testing.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
```

**Comment by cf512** [comment]
A quick note on why issues are being closed would be helpful. At a glance, looks like because this one was already resolved.

**Comment by romadrutskii** [comment]
> A quick note on why issues are being closed would be helpful. At a glance, looks like because this one was already resolved.

yes, sorry. there were a commit that fixed this.
