### ISSUE TITLE
Python params for querystring should be dictionary

### ISSUE THREAD

**Issue by salman2learn** [NickCarneiro/curlconverter#93]
Currently params are generated as:
```
params = (
   ('key1', 'value1'),
   ('key2', 'value2')
)
```

It should be:
```
params = {
   'key1': 'value1',
   'key2': 'value2'
}
```

Otherwise, the error stack is:

```
Traceback (most recent call last):
  File "./myscript.py", line 29, in <module>
    response = requests.get('https://www.someurl.com/....', headers=headers, params=params, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 52, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 40, in request
    return s.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 213, in request
    args[attr] = merge_kwargs(local_val, session_val)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 44, in merge_kwargs
    for (k, v) in list(local_kwarg.items()):
AttributeError: 'set' object has no attribute 'items'
```

**Comment by NickCarneiro** [comment]
Can you post the command?

**Comment by NickCarneiro** [comment]
We switched back to dicts in https://github.com/NickCarneiro/curlconverter/issues/96
Closing this. Hope the change works out for you.
